"""每日自動化的順序控制；domain action 仍由 composition root 注入。"""

from __future__ import annotations

from typing import Any, Mapping, Protocol


class DailyAutomationActions(Protocol):
    """每日流程需要的 actions；不在此模組綁定 I/O 實作。"""

    def should_skip_non_trading_day(self, config: Mapping[str, Any]) -> bool: ...
    def skip(self, step_name: str, reason: str) -> None: ...
    def non_trading_day_reason(self) -> str: ...
    def guard_resource_profile(self) -> None: ...
    def preflight(self) -> None: ...
    def run_etl(self) -> None: ...
    def validate_data(self) -> None: ...
    def record_data_freshness(self) -> None: ...
    def run_ranking(self) -> None: ...
    def record_ranking(self) -> None: ...
    def expected_ranking_path(self) -> Any: ...
    def run_candidate_persistence(self, config: Mapping[str, Any], ranking_path: Any) -> None: ...
    def run_weekly_snapshot(self, config: Mapping[str, Any], ranking_path: Any) -> None: ...
    def run_market_context(self, config: Mapping[str, Any]) -> None: ...
    def run_daily_recommendation_performance(self, config: Mapping[str, Any]) -> None: ...
    def run_decision_quality(self, config: Mapping[str, Any], ranking_path: Any) -> None: ...
    def run_daily_performance_review(self, config: Mapping[str, Any]) -> None: ...
    def run_gross55_shadow_monitor(self, config: Mapping[str, Any], ranking_path: Any) -> None: ...
    def run_capital_entry_quality_shadow_monitor(self, config: Mapping[str, Any], ranking_path: Any) -> None: ...
    def run_candidate_trail10_shadow_monitor(self, config: Mapping[str, Any], ranking_path: Any) -> None: ...
    def run_overlap_first_recommendation_shadow(self, config: Mapping[str, Any], ranking_path: Any) -> None: ...
    def run_shadow_historical_evidence_report(self, config: Mapping[str, Any]) -> None: ...
    def run_daily_shadow_status_report(self, config: Mapping[str, Any]) -> None: ...
    def record_api_cache_clear_skipped(self) -> None: ...
    def run_postcheck(self, config: Mapping[str, Any]) -> None: ...
    def run_daily_report(self, config: Mapping[str, Any], ranking_path: Any) -> Any: ...
    def run_clawd_payload(self, config: Mapping[str, Any], report_path: Any) -> None: ...


def run_daily(actions: DailyAutomationActions, config: Mapping[str, Any]) -> None:
    """依既有 production 順序執行每日主要流程。"""

    if not config.get("enabled", True):
        actions.skip("daily.disabled", "config daily.enabled=false")
        return
    if actions.should_skip_non_trading_day(config):
        actions.skip("daily.trading_day_gate", actions.non_trading_day_reason())
        return

    actions.guard_resource_profile()
    actions.preflight()
    actions.run_etl()
    actions.validate_data()
    actions.record_data_freshness()
    actions.run_ranking()
    actions.record_ranking()
    ranking_path = actions.expected_ranking_path()
    actions.run_candidate_persistence(config, ranking_path)
    actions.run_weekly_snapshot(config, ranking_path)
    actions.run_market_context(config)
    actions.run_daily_recommendation_performance(config)
    actions.run_decision_quality(config, ranking_path)
    actions.run_daily_performance_review(config)
    actions.run_gross55_shadow_monitor(config, ranking_path)
    actions.run_capital_entry_quality_shadow_monitor(config, ranking_path)
    actions.run_candidate_trail10_shadow_monitor(config, ranking_path)
    actions.run_overlap_first_recommendation_shadow(config, ranking_path)
    actions.run_shadow_historical_evidence_report(config)
    actions.run_daily_shadow_status_report(config)
    actions.record_api_cache_clear_skipped()
    actions.run_postcheck(config)


def run_daily_final_artifacts(actions: DailyAutomationActions, config: Mapping[str, Any]) -> None:
    """狀態先落盤後，依既有順序產出報告與 publish-ready payload。"""

    ranking_path = actions.expected_ranking_path()
    report_path = actions.run_daily_report(config, ranking_path)
    actions.run_clawd_payload(config, report_path)
