"""跨 API、service、前端共用的資料契約。"""

from .backtest import BacktestArtifact, BacktestReportSummary, BacktestSummaryResponse
from .fundamental import (
    FundamentalDimensionSummary,
    FundamentalMetricItem,
    FundamentalSourceLinks,
    FundamentalTrendItem,
    FundamentalWarningItem,
    StockFundamentalsResponse,
)
from .market import (
    ApiHealth,
    LatestRankingResponse,
    RankingItem,
    StockBar,
    StockOhlcvResponse,
)
from .monitoring import FactorMetricContract, FactorMonitorResponse
from .reference import (
    ExposureBreakdownItem,
    RankingReferenceSummary,
    StockConceptMembership,
    StockEtfExposure,
    StockIndustryClassification,
    StockReferenceResponse,
    TradableUniverseItem,
    TradableUniverseResponse,
)
from .stock_detail import (
    StockDetailBacktestSection,
    StockDetailFundamentalSection,
    StockDetailPriceSection,
    StockDetailReferenceSection,
    StockDetailResponse,
    StockDetailTradePlanSection,
    StockPatternOverlayLine,
    StockPatternSignal,
)
from .trading import MarketRegimeContract, TradePlanContract
from .weekly import (
    InvestmentSettingsContract,
    OpportunityComponentContract,
    WeeklyCandidateContract,
    WeeklyCandidateLayerContract,
    WeeklyCandidatesResponse,
    WeeklyChangeContract,
    WeeklyMarketSummaryContract,
    WeeklyModelPoolItemContract,
    WeeklySettingsEffectContract,
    WeeklySnapshotContract,
)

__all__ = [
    "ApiHealth",
    "BacktestArtifact",
    "BacktestReportSummary",
    "BacktestSummaryResponse",
    "LatestRankingResponse",
    "FundamentalMetricItem",
    "FundamentalDimensionSummary",
    "FundamentalSourceLinks",
    "FundamentalTrendItem",
    "FundamentalWarningItem",
    "FactorMetricContract",
    "FactorMonitorResponse",
    "ExposureBreakdownItem",
    "MarketRegimeContract",
    "InvestmentSettingsContract",
    "OpportunityComponentContract",
    "RankingReferenceSummary",
    "RankingItem",
    "StockBar",
    "StockDetailBacktestSection",
    "StockDetailFundamentalSection",
    "StockDetailPriceSection",
    "StockDetailReferenceSection",
    "StockConceptMembership",
    "StockDetailResponse",
    "StockDetailTradePlanSection",
    "StockEtfExposure",
    "StockFundamentalsResponse",
    "StockIndustryClassification",
    "StockOhlcvResponse",
    "StockPatternOverlayLine",
    "StockPatternSignal",
    "StockReferenceResponse",
    "TradableUniverseItem",
    "TradableUniverseResponse",
    "TradePlanContract",
    "WeeklyCandidateContract",
    "WeeklyCandidateLayerContract",
    "WeeklyCandidatesResponse",
    "WeeklyChangeContract",
    "WeeklyMarketSummaryContract",
    "WeeklyModelPoolItemContract",
    "WeeklySettingsEffectContract",
    "WeeklySnapshotContract",
]
